require("core.plugin_cfg.nvim-tree")
require("core.plugin_cfg.colorscheme")
require("core.plugin_cfg.lualine")
require("core.plugin_cfg.telescope")
require("core.plugin_cfg.lspconfig")
-- require("core.plugin_cfg.treesitter")
