require("core.plugin_cfg.nvim-tree")
require("core.plugin_cfg.nightfox")
-- require("core.plugin_cfg.catppuccin")
-- require("core.plugin_cfg.kanagawa")
require("core.plugin_cfg.lualine")
-- require("core.plugin_cfg.feline")
require("core.plugin_cfg.telescope")
require("core.plugin_cfg.lspconfig")
-- require("core.plugin_cfg.treesitter")
