vim.keymap.set('n', "<C-h>", ":bprev <CR>", noremap)
vim.keymap.set('n', "<C-l>", ":bnext <CR>", noremap)
vim.keymap.set('n', "<C-j>", ":m+<CR>==", noremap)
vim.keymap.set('n', "<C-k>", ":m-2<CR>==", noremap)
vim.keymap.set('i', "<C-j>", "<Esc>:m+<CR>==gi", noremap)
vim.keymap.set('i', "<C-k>", "<Esc>:m-2<CR>==gi", noremap)
vim.keymap.set('v', "<C-j>", ":m'>+<CR>gv=gv", noremap)
vim.keymap.set('v', "<C-k>", ":m-2<CR>gv=gv", noremap)
vim.keymap.set('n', "<C-u>", "<C-u>zz", map)
vim.keymap.set('n', "<C-d>", "<C-d>zz", map)
vim.keymap.set('n', "<Esc><Esc>", ":nohlsearch<CR>", noremap)
